name: Trading Bot Run

on:
  schedule:
    - cron: '*/5 6-17 * * *'
    - cron: '0,5,10,15,20,25,30 18 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      CC_API_KEY: ${{ secrets.CC_API_KEY }}
      CC_IDENTIFIER: ${{ secrets.CC_IDENTIFIER }}
      CC_PASSWORD: ${{ secrets.CC_PASSWORD }}
      BASE_URL: https://demo-api-capital.backend-capital.com
      MARKET_ID: BTCUSD
      RESOLUTION: MINUTE_5
      TRADE_SIZE: 0.01
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python with pip cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot script
        run: python main_1.1.py
